---
title: "project2"
author: "Aksel Vincent Berg & Sergi Alonso"
date: "5/30/2018"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Split the file into training set and test set.

```{r}

training_set <- read.csv("datos_MGTN.csv", nrows=650, header=FALSE)

test_set <- read.csv("datos_MGTN.csv", skip=650, header=FALSE)

```


Task 1: Obtain the mean of the traning set temperature mew_T.

```{r}

data_training_set <-data.frame(training_set)

mean_temperature_training <- mean(data_training_set[,"V4"])

```


Task 2: Obtain the standard deviation (std) of the training set temperature mew_T.

```{r}

sd_temperature_training <- sd(data_training_set[,"V4"])

```


Task 3: Normalize all the samples of the training.

```{r}
n = 650

# Repeat the process for ozone, resistor data and relative humidity.

mean_ozone_training <- mean(data_training_set[,"V2"])
sd_ozone_training <- sd(data_training_set[,"V2"])

mean_resistor_training <- mean(data_training_set[,"V3"])
sd_resistor_training <- sd(data_training_set[,"V3"])

mean_humidity_training <- mean(data_training_set[,"V5"])
sd_humidity_training <- sd(data_training_set[,"V5"])

temp_norm_training_set <- array(dim=n)
ozone_norm_training_set <- array(dim=n)
resistor_norm_training_set <- array(dim=n)
humidity_norm_training_set <- array(dim=n)

# Subtract the mean and devide by the standard deviation.
for (i in 1:650) {
    temp_norm_training_set[i] <- (data_training_set[,"V4"][i] - mean_temperature_training) / sd_temperature_training
    
    ozone_norm_training_set[i] <- (data_training_set[,"V2"][i] - mean_ozone_training) / sd_ozone_training
    
    resistor_norm_training_set[i] <- (data_training_set[,"V3"][i] - mean_resistor_training) / sd_resistor_training
    
    humidity_norm_training_set[i] <- (data_training_set[,"V5"][i] - mean_humidity_training) / sd_humidity_training
    
}

data_test_set <-data.frame(test_set)

temp_norm_test_set <- array(dim=350)
ozone_norm_test_set <- array(dim=350)
resistor_norm_test_set <- array(dim=350)
humidity_norm_test_set <- array(dim=350)

for (i in 1:350) {
        temp_norm_test_set[i] <- (data_test_set[,"V4"][i] - mean_temperature_training) / sd_temperature_training
    
    ozone_norm_test_set[i] <- (data_test_set[,"V2"][i] - mean_ozone_training) / sd_ozone_training
    
    resistor_norm_test_set[i] <- (data_test_set[,"V3"][i] - mean_resistor_training) / sd_resistor_training
    
    humidity_norm_test_set[i] <- (data_test_set[,"V5"][i] - mean_humidity_training) / sd_humidity_training
}


```




Task 2: Project Realization (Practical Part I)


Task 2.1

```{r}

plot(data_training_set[,"V3"], type="l")

plot(data_training_set[,"V2"], type="l")

```




```{r}

plot(ozone_norm_training_set, resistor_norm_training_set)


```



Task 4.
```{r}

fit_ozone_norm <- lm(ozone_norm_training_set ~ temp_norm_training_set + resistor_norm_training_set + humidity_norm_training_set)
summary(fit_ozone_norm)

ozone_predicted <- predict(fit_ozone_norm)
RMSE = 0
for (i in 1:650) {
    RMSE = RMSE + (ozone_predicted[i]*sd_ozone_training+mean_ozone_training - data_training_set[,"V2"][i])**2
}

RMSE = sqrt(1/650 * RMSE)
print(RMSE)

#predict(fit_ozone_norm)
plot(predict(fit_ozone_norm), type="l")

```

The obtained values from the training set:
- RMSE: 14.75
- R^2: 0.8813


TASK 5

```{r}

myData <- data.frame(c(temp_norm_test_set), c(resistor_norm_test_set), c(humidity_norm_test_set))
colnames(myData) <- c("temp_norm_training_set", "resistor_norm_training_set", "humidity_norm_training_set")

test_data_prediction <- predict(fit_ozone_norm, newdata=myData)
plot(test_data_prediction, type="l")

RMSE = 0
for (i in 1:350) {
    RMSE = RMSE + (test_data_prediction[i]*sd_ozone_training+mean_ozone_training - data_test_set[,"V2"][i])**2
}

RMSE = sqrt(1/350 * RMSE)
print(RMSE)

```


```{r}


beta1 = 0.43
beta2 = 0.67
beta3 = 0.05

test <- array(dim=350)

for (i in 1:350) {
    test[i] <- beta1 * temp_norm_test_set[i] + beta2 * resistor_norm_test_set[i] + beta3 * humidity_norm_test_set[i]
}

RMSE = 0
for (i in 1:350) {
    RMSE = RMSE + (test[i]*sd_ozone_training+mean_ozone_training - data_test_set[,"V2"][i])**2
}

RMSE = sqrt(1/350 * RMSE)
print(RMSE)

```


